### ISSUE TITLE
sendpayment.py "Non-hexadecimal digit found"

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#582] opened 2016-06-21 05:38 UTC
`python sendpayment.py --yes -N4 --rpcwallet "" 4100000      19Fg5KQdbPwsYwXZG6wYtgSBdjgk4DA3fQ`

Crashes with:
```
  File "sendpayment.py", line 314, in main
    irc.run()
  File "/home/user/bin/joinmarket-master/joinmarket/irc.py", line 657, in run
    self.__handle_line(line)
  File "/home/user/bin/joinmarket-master/joinmarket/irc.py", line 540, in __handle_line
    self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
  File "/home/user/bin/joinmarket-master/joinmarket/irc.py", line 491, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "/home/user/bin/joinmarket-master/joinmarket/irc.py", line 346, in __on_privmsg
    self.on_pubkey(nick, maker_pk)
  File "/home/user/bin/joinmarket-master/joinmarket/taker.py", line 584, in on_pubkey
    self.cjtx.start_encryption(nick, maker_pubkey)
  File "/home/user/bin/joinmarket-master/joinmarket/taker.py", line 96, in start_encryption
    my_btc_pub = btc.privtopub(my_btc_priv)
  File "/home/user/bin/joinmarket-master/bitcoin/secp256k1_main.py", line 269, in privkey_to_pubkey
    return privkey_to_pubkey_inner(priv, usehex)
  File "/home/user/bin/joinmarket-master/bitcoin/secp256k1_main.py", line 228, in func_wrapper
    newargs += [arg.decode('hex')]
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found

done
```

Any assistance gratefully received.

**Comment by AlexCato** [comment] 2016-06-21 20:25
I've just copy & pasted your command (only replaced the address of course) and it seems to work for me.
At which point does it crash? Right away? While performing the transaction building? Is this reproducible or did it just happen once, then worked other times?

Maybe you had an invisibile character in that line somewhere, which sometimes accidently happens when hitting a wrong key or marking slightly more text while copying to clipboard...

**Comment by AdamISZ** [comment] 2016-06-22 09:28
Seems likely to be related to what was fixed in #521 . If you aren't running from current develop branch, I suggest doing so.

But to be sure that that was the cause, would need to look in the log.  You want to see whether your counterparty sent an invalid encryption pubkey (it should be 32 bytes, so 64 hex chars)

**Comment by HamishMacEwan** [comment] 2016-06-22 09:42
Firstly to Alex's questions

1. When does it happen? - After accepting the offers and providing the Bitcoin Core password
2. Is it reproducible? - Yes, but I gave up trying since it appeared to be a bit beyond my competence to diagnose or remedy.

Adam, I'm running, as far as my git foo takes me, `HEAD detached at v0.1.4`  I'll try and catch-up.

I've got a couple of things to check, thanks for the impulse to dive into the log.

**Comment by AdamISZ** [comment] 2016-06-22 09:50
Yes so you're running the latest release. I'll double check but I think you're looking for something like:

    <<privmsg nick=Quwuleqit message = !pubkey 815285c7cd4a8bb2c721fec03992b0c0fb7377356ba380d1bb6a561def77cd59

However if it is reproducible, then that's a concern. My guess as to the cause may end up being entirely wrong.

**Comment by HamishMacEwan** [comment] 2016-06-22 10:13
This might be a more useful excerpt from the log:

```
2016-06-22 22:02:24,023 [MainThread  ] [DEBUG]  <<privmsg nick=Sagoxugod message=!pubkey c14f540a678342b84c96f08e7ec9488ed749529b709944b4b36b4e795d51ef6e
2016-06-22 22:02:24,023 [MainThread  ] [DEBUG]  rpc: getwalletinfo []
Enter passphrase to unlock wallet: 
2016-06-22 22:02:30,149 [MainThread  ] [DEBUG]  rpc: dumpprivkey [u'1GD5MA47kgtbSD5pSPMJ4fM3VapmJuG7SV']
2016-06-22 22:02:30,172 [MainThread  ] [DEBUG]  CRASHING, DUMPING EVERYTHING
2016-06-22 22:02:30,172 [MainThread  ] [DEBUG]  Class debug dump, name:BitcoinCoreWallet
2016-06-22 22:02:30,172 [MainThread  ] [DEBUG]  key=fromaccount
2016-06-22 22:02:30,172 [MainThread  ] [DEBUG]  string: len:0
```

**Comment by AdamISZ** [comment] 2016-06-22 10:15
If you do dumpprivkey on the command line, does it show what looks like a sensible private key in WIF format?

I'd be interested to hear if others (or you?) have been using the rpcwallet option successfully recently (in particular since 0.1.4)

**Comment by HamishMacEwan** [comment] 2016-06-22 10:21
1. No, it complains `Method not found (code -32601)`
2. Well Alex has, and I've only had this grief (with that specific address) since the 21st of June. I can't recall when I used it successfully before then.

**Comment by AlexCato** [comment] 2016-06-22 14:02
Needs more testing than I did, as I didnt complete a full transaction. Just checked that it doesnt crash until I can pick offers, as i assumed (incorrectly) that you crash before that.

**Comment by HamishMacEwan** [comment] 2016-06-26 02:44
There doesn't seem to be a connection with the other issue, after sorting that one, the result differs only in the Bitcoin address that triggers the crash:
```
2016-06-26 14:34:11,984 [MainThread  ] [DEBUG]  rpc: getwalletinfo []
Enter passphrase to unlock wallet: 
2016-06-26 14:34:37,379 [MainThread  ] [DEBUG]  rpc: dumpprivkey [u'1Nx1VDfnNL2kryG6fnmzSxD1A4SEkWXCb4']
2016-06-26 14:34:37,380 [MainThread  ] [DEBUG]  CRASHING, DUMPING EVERYTHING
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  Class debug dump, name:BitcoinCoreWallet
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  key=fromaccount
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  string: len:0
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  key=utxo_selector
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  <function select at 0x7faf0884f848>
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  key=max_mix_depth
2016-06-26 14:34:37,381 [MainThread  ] [DEBUG]  1
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  Class debug dump, name:SendPayment
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  key=maker_pks
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  {}
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  key=makercount
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  4
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  key=chooseOrdersFunc
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  <function weighted_order_choose at 0x7faf098ec1b8>
2016-06-26 14:34:37,382 [MainThread  ] [DEBUG]  key=cjtx
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  <joinmarket.taker.CoinJoinTX object at 0x7faf07d3c550>
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  key=db
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  <sqlite3.Cursor object at 0x7faf084870a0>
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  key=mixdepth
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  0
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  key=waittime
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  5
2016-06-26 14:34:37,383 [MainThread  ] [DEBUG]  key=wallet
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  <joinmarket.wallet.BitcoinCoreWallet object at 0x7faf07d06610>
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  key=amount
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  100000
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  key=destaddr
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  string: len:34
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  1PucvkhJURMcLDtyaQhhincT9qy5JHGbU8
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  key=msgchan
2016-06-26 14:34:37,384 [MainThread  ] [DEBUG]  <joinmarket.irc.IRCMessageChannel object at 0x7faf07d06750>
2016-06-26 14:34:37,385 [MainThread  ] [DEBUG]  key=txfee
2016-06-26 14:34:37,385 [MainThread  ] [DEBUG]  5000
2016-06-26 14:34:37,385 [MainThread  ] [DEBUG]  key=answeryes
2016-06-26 14:34:37,385 [MainThread  ] [DEBUG]  True
2016-06-26 14:34:37,415 [MainThread  ] [DEBUG]  Traceback (most recent call last):
  File "sendpayment.py", line 314, in main
    irc.run()
  File "/home/macewanh/bin/joinmarket-master/joinmarket/irc.py", line 657, in run
    self.__handle_line(line)
  File "/home/macewanh/bin/joinmarket-master/joinmarket/irc.py", line 540, in __handle_line
    self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
  File "/home/macewanh/bin/joinmarket-master/joinmarket/irc.py", line 491, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "/home/macewanh/bin/joinmarket-master/joinmarket/irc.py", line 346, in __on_privmsg
    self.on_pubkey(nick, maker_pk)
  File "/home/macewanh/bin/joinmarket-master/joinmarket/taker.py", line 584, in on_pubkey
    self.cjtx.start_encryption(nick, maker_pubkey)
  File "/home/macewanh/bin/joinmarket-master/joinmarket/taker.py", line 96, in start_encryption
    my_btc_pub = btc.privtopub(my_btc_priv)
  File "/home/macewanh/bin/joinmarket-master/bitcoin/secp256k1_main.py", line 269, in privkey_to_pubkey
    return privkey_to_pubkey_inner(priv, usehex)
  File "/home/macewanh/bin/joinmarket-master/bitcoin/secp256k1_main.py", line 228, in func_wrapper
    newargs += [arg.decode('hex')]
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
```
This time though, `dumprivkey 1Nx1VDfnNL2kryG6fnmzSxD1A4SEkWXCb4` does have a sensible output.  As does `dumpprivkey 1GD5MA47kgtbSD5pSPMJ4fM3VapmJuG7SV` from the earlier report.  It would seem my cold affected me more than I thought.

**Comment by AdamISZ** [comment] 2016-09-15 11:16
This is probably related to 6a8633871a0fa4244b75f736bd03267c8932ed7b ; if so, it should now be fixed. Otherwise feel free to re-open.

**Closed by AdamISZ** 2016-09-15 11:16 UTC
