### ISSUE TITLE
txid=... not being listened for

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#488] opened 2016-04-01 06:25 UTC
With a ton of socks errors.
This is how a usual tumbler run looks like for me.
http://pastebin.com/1i27H4Yi

**Comment by chris-belcher** [comment] 2016-04-05 18:01
Looks like tumbler sent a single transaction which was never confirmed according to that log.

Find the txid (e.g. on line 263) and put it into a blockchain explorer, was it ever mined into a block?

**Comment by dreboli** [comment] 2016-04-05 19:49
I didn't even notice the `transaction not found, probably a conflict`. The other errors were probably because of connectivity issues I think.
So this makes it 8 fails out of 8 tries because of that same problem, see here https://github.com/JoinMarket-Org/joinmarket/issues/451#issuecomment-205962633

**Comment by chris-belcher** [comment] 2016-05-03 19:22
closing as duplicate

**Closed by chris-belcher** 2016-05-03 19:22 UTC
Labels: Crash
