### ISSUE TITLE
Sendpayment: error(32, 'broken pipe') during tx signing.

### ISSUE THREAD

**Issue by tailsjoin** [JoinMarket-Org/joinmarket#307] opened 2015-11-05 15:45 UTC
I've notice that when trying to create larger transactions with multiple inputs and makers that used to go through without a problem are now getting an error in the midst of receiving signatures that causes my bot to restart the tx from the beginnning in a loop. This is the error:

    error(32, 'Broken pipe')
    disconnected irc

Here is a redacted log starting at receiving the sigs: https://paste.debian.net/?show=324055;lines=0

**Comment by tailsjoin** [comment] 2015-11-05 16:56
Update: this `MAX_PRIVMSG_LEN = 400` is the problem from `lib/irc.py`. I increased mine to `4000` and ran the same sendpayment. I get no error, but my maker bot that was part of the tx had this in the console:

    [timestamp] message not a cmd
    [timestamp] message not a cmd

The bot doing the sendpayment just hung after all sigs came in and then started the tx over after the timeout thread.

**Comment by AdamISZ** [comment] 2015-11-05 18:58
MAX_PRIVMSG_LEN is not a maximum length of a message, but a maximum line length for ic messages. larger messages are chunked and sent on multiple lines.

**Comment by AdamISZ** [comment] 2015-11-05 18:59
IIRC that 400 comes from some IRC limit, but not sure what that is (also may well be different on different servers).

**Comment by tailsjoin** [comment] 2015-11-05 19:35
I couldn't even sweep a depth with `-N 3` because of this error. Not until I broke up my utxos into multiple txs, and then added makers did it finally work.

**Comment by AdamISZ** [comment] 2015-11-05 19:42
@tailsjoin did you reset MAX_PRIVMSG_LEN to 400?

**Comment by tailsjoin** [comment] 2015-11-05 19:47
Yes.

**Comment by Xangst** [comment] 2015-11-06 18:54
I also have this error today multiple time when trying to send. I finally made the transaction go through by using only the most expensive makers with no other changes. Definitely tied to utxos.

**Comment by AdamISZ** [comment] 2015-11-06 20:58
@Xangst just to help with this, could you let us know how many makers you were joining with?

I would suggest this is most likely due to flooding, but I really don't know at the moment, and @tailsjoin reporting it with -N 3 doesn't help that case. Such things have been reported before, but I haven't seen them personally.

**Comment by Xangst** [comment] 2015-11-06 21:11
I do not remember if it was -N 4 or -N 5, but it does not matter. I have increased the wait time to 5 seconds between messages to prevent flooding. 

I have been using this project for a few months and I have not had the need for maybe 1 or 1.5 months. After pulling fresh today and running into this issue repeatedly I have to say usability has gone way down. I used to do -N 7 as a minimum. Now I struggle to do anything.

Bot Tobayidaw is the main culprit. I am trying to sweep a depth right now and I get this garbage:

    [2015/11/06 20:53:36] rpc: gettxout ['37f83190c34a6cf685c1df908ad415f727058a295ed4c965487aab64640ce908', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['85eadc399560c544aa06e7ac85d003c5c0506b29ebe866bb721bfe59899fdd69', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['7c74bb3c56fe4bb54f14f2b5bda6bb198c547907d41366df8de15864350b3fdd', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['1ae00d515bbe991587e87df17139433f86143b7860971f1668dcf84ba341b346', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['c7e3a9d5ece60a90fe214ed492b919f36696bb1db61075e7b2944a8befaa54a2', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['50e3ab3784e114d732d84763c46ec408a4fb4867cbcd61afb65c00c5240a1884', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['f7b880c6b727d102430191ae7534a3679e4a703c917b8402b7aace0a5118c2ad', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['c5899da915403b4c889b7cce95f9affea4de445934a6fc7919a289190430f9ff', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['7f8961f247a41560ee58e9301e90a72ff7a7db5e9fc0c421de5db0535cf42212', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['d5af4fb50d42234cd6b5755a0dc233975ac9132a2a41712f5a94c456d25737d8', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['7989c50d46d4db05fbef01a894e222255966dc0d7626938222a10813773df16f', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['6ea93b82e5ea841aa18730fd9dcb9ddea02ebfff2df5dac4a95a6d086d3fe675', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['279d5d3794d16b2c6bf9579099106deec4a77435e9fab283e1c874702570cae6', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['a04dcd0dece51a23a178cf8a88ace3613944800091eaa46a529a15ebe879024e', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['72792b64fd0a8f03b1c1e9f29165e971925b58b3783e6a7cfcc5c1a21fd8178d', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['31c92ab5e986b49a96866fb3a406e5ee82b14a2a5525b96f71e43a0fda6a5488', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['05624a10f0c437704e790446090586ff88dc91399592707a19a131533cfbcdc2', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['539ad6ab5d63a7f253fe9162622ee903300741f465cecf546232a4db9c7a0d81', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['50275b0e3feb761e24f048c53bb5517ab4c5bafafec9ccfe1894eceef44db9d0', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['37ad569351f02c0f4ff767aa53216476d5e6d1139ef368d9b36daa1dd9799e89', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['da6d63ce0a27592ffafc6f024a2a7444861d67e5d0f7dc14be4a2f0f8ba8f80e', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['b91c4abd650ac1b4d81d7580fef1d25b97bbc32d6314b3064fddfe5b764a143d', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['79e1f6826a0067d5a139e213844b8e5bd1f2eab8fcc0b46036897323e12da7bf', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['6fbed896304281873a923e930ee1c7992caa6ee240cbd099cd5bb188df556a18', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['c8d219670cac5ba72d607ec6e8d22451ca069ca19e62b05322faa4eb8e48ea7f', 7, False]
    [2015/11/06 20:53:36] rpc: gettxout ['fb72f0da002e8713d5c7b02f3bc81224ef914e73fd02fbd84555dedfa6be6d52', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['30dac72ab9ab3710a1b0aeb1e2cea9dc4708d6d8b32b871a2722550be5b1265d', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['cdcbf9b6b24c5b93b3bfc7caae21a01c8304cc3d3991c7272e01c2a19e6a3d72', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['e1998e253b47dabaf086b86ca2d781a948e12a6113b9b4b515d587e0e3581861', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['9b789a10914593f99c401280406dbf094a784431364486737b183bd43ae4df4c', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['302f6e9723e847f11f63c3f69cec5e2ff674c859e19327b78db6c354056acbbe', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['c65b9afb292627369922b48eacbb6286db51c618fade0e2c6a5dec964b942798', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['48488d70d181c3617a65893cd9e45fa6a8b14129ef6ee69b078b3c6030467cde', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['a4001c9daf2c0362e233ec674f53c0cbb6a8c0913b331bec2a98753eb60c3790', 7, False]
    [2015/11/06 20:53:36] rpc: gettxout ['4beacdbbf1b2bd1713847f74ae15226be0c4dd8628b3aa676f746b2f8cbc4771', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['6f78af3d3cec1d2e6d59d4fb874dc974e184412ad1b350c2faed2c92f0090cf2', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['d9ea4e689b50a9114a7147d83639c059db11bdbe9fb8a3bc4ff63bd847308151', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['b9663b73ec3ca110d01d9cd1e6ff9d6133eaaf9235133f8e1ec821494d2829b1', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['a43347f9800fb5cee3a6b764a298f597646419f981f6d53daa6f59423dbefa9b', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['d2f2526d9451a83f716f7d44fbd795f87fcaa292243802ee2c7df6e2d3d02e94', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['e374683616260d97cbf9c1d40c3baa674e5694028e3be19aba9bd168c45a4d50', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['dd060da7230d0c6fe95071ab8fe564fd2f55afb8bc5965c4c42052803992c813', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['7511ebc1d09c92d4864bac35b0a1213592931c246e843817966d1396c65a499d', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['9375cf455d741c66d09028239a3193a63639ed6aac688c77ae1dee7202e9273c', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['2d8a48155742e04389a81e3fb5e069018ed5173276ba6c733e64d0fb5826f9f7', 11, False]
    [2015/11/06 20:53:36] rpc: gettxout ['d636ce40128d18a3be72f2201f4c3d0c5a1665141fd40c0a45e3908809c4e7c4', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['e185471ba26df14bac19d32c995194ee502beb6c505b51b80ae7fe521428f00c', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['79b7cd4a782dea114cca22b9702cff3e9492fb08b19c1b1fa8d23f6069e3ef51', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['1b352d36d4a8fbadbc356297174f2ac396fda1e3fd3685ddde1edb0a0a8d83f9', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['15fc5250701268b60c0c41b0ff2f372add126a5ceeb30190b4ed14daf0ad1af7', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['eec707507408eedd200e64cbaf57dacb038b1adc68aed2030cd72ce48c83fe80', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['8fd19c0ab81caaba487ee5b1aae78d4be7f1abab7675665d6a7e4c54c17d88d8', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['3c160ff36341b5650f6ce45cde18909bffc589f5d3fac12c6617d4015475a9bf', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['5ebf55fa4b3f2f737300ea16cfaef41e837aaa2eeaa5ae93fd833e9cbec89b55', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['fb6f69643e7953c782e0189f2de5985f276c72003ee715a0b2d5a562e753cfda', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['45cb390014ee41a69dcc388683bb4c34ef1d3a9582e91ef8acb28e4511570126', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['308c961a3b4c23a21ca12bfc183217646cfb35ad8f6a08dbbfef0995175629b6', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['203d46a9bb443a774736ca381d1febf99d9ccf799040ff0fb8974df7c5e8e588', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['5a6004a308c27dae41cb30137be3f5449b864b43ec552de1d14cbc2f120fa69e', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['40f6fcb9cf101b95370853a76f9a873966f62f64a9eb607dc35b19b1eafede41', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['cd7faebbb6a8d751e3bc343dfd6094056ec7192e1ed6428b7e190756e9642037', 7, False]
    [2015/11/06 20:53:36] rpc: gettxout ['41969e6339de55a0ed175f9f5ac92cc539071b61ef705646358909ea44cf328b', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['2c877aeb8720affac6d0c099f351705d293312830237688a6a74eb1eefd08fa3', 7, False]
    [2015/11/06 20:53:36] rpc: gettxout ['3ee6b7173a744b8d37896b46723290d8e507d66446233a960a16e360b1518438', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['de21fb99b9b7e608b0f68cfc0c7db3c51fb8bea3efe994b1407ce5dae1ec56cb', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['f8a682ef3120860f0dcec3fe59ca951f40b1b9307836f7e421038046393f89f0', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['8b1e877ad3c15a79c6364048a8efe6ad24f62249025069111e9e031e1a475284', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['e9f68dbc6af060d61c73ba87f46d906a1d85f45f7ce801ef3cb21543fcb6000f', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['153d7b8a53c1304c8599fac973035b7cfea94ae321486bc220529b49b83810f7', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['457262d0c7d36be7c0f4bdb5339a2f812f7d57813959fc2561eb605b8b3ae5fb', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['57eb74e7b67ecfe743b0ea0f96c931fa3e0248ea6e3fc1d980691e1926b60648', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['bd402764136070304816372d5026a60c46bd0b0cd0dfc4df2399aa61e9e48223', 7, False]
    [2015/11/06 20:53:36] rpc: gettxout ['f2211b22307564d00c9498332cdc49c601e12e85c461d63f5aaaacc9eeb7ffa8', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['f740249abc57f94709048c9ca985eb44ba27b6c84e812dcdcc1faafcab8b1121', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['5715cea62dd692d97033e276ec2d9fa3f32c8be6aea617a7166c5f83a9f98c7a', 7, False]
    [2015/11/06 20:53:36] rpc: gettxout ['cf293070096bc21aba74400003f4ea94019feb7ab47ac11c43069f339382a858', 0, False]
    [2015/11/06 20:53:36] rpc: gettxout ['66a6a4e50a8c632762aa52ce32b994c3ef02f5ae483bec39cde99b856b3aca43', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['8fadfd5eb7fcde9d88f8215a0569591a3fb8fa007c552c109bc86f8eabfca581', 8, False]
    [2015/11/06 20:53:36] rpc: gettxout ['b86d5ba4c710bc30d2546aa469b8945414b1671295efb57230e8fc0717479645', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['86d90fdf154d51796fce3f83ad36e1426efa214d1e6ffcd40a591e10dd023111', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['b9250c995126b0a2f1b2c411dcdb4a68a543a76edb117f698f23ee809d27edbc', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['e00dc42a9e5ad2c0fb47365df5bc8bbb83bb359ca4d265ba2f7d6ee51cd2f5fd', 5, False]
    [2015/11/06 20:53:36] rpc: gettxout ['262de958cb70b6d9ab2ddcda8658402ebe2fe7a50b97d49be4ef953e6e4159c2', 8, False]
    [2015/11/06 20:53:36] rpc: gettxout ['4d577e219037366aede65498955578389286cec8f961839242dae8953b40273d', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['7656140f7c8138b1664229b39eb64c78dc80c0441ffad603ecbc5233af81c78d', 2, False]
    [2015/11/06 20:53:36] rpc: gettxout ['ed2ff21f9d2b85549a4a1f7146225112d0d1b6e18e968308d8d18f0746503c6f', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['d9fdd99495155f085831fc9052633580edbf3c364be0297610b1d46de2e7e964', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['791b6ad5e921772f61fdf75a44694325e7c76760306dcf18976cac5d72095676', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['e0544b49f555407304cb214fcaab76297a67d8e1ca88369717db8eeae358450d', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['407409bb40a70bcae9f7ab817c59873b7c151e270be95930490e2a5ee5767a58', 6, False]
    [2015/11/06 20:53:36] rpc: gettxout ['63d56a281cd61f59f59e0debf52487ca4cfff8dc7384e1a2b477ece555162e66', 1, False]
    [2015/11/06 20:53:36] rpc: gettxout ['99279fe0994c1a49c2ce88ac97c4f21bb50a4bc9b0cb27bb0bc22df62cdac098', 4, False]
    [2015/11/06 20:53:36] rpc: gettxout ['caae9adddce1310fdd4194840e2c67f02934d601fb59b6eebc03e9a4ba1df467', 9, False]
    [2015/11/06 20:53:36] rpc: gettxout ['f389bb277a8eb55641e7185ed75fb7ec9061ff4217c268d8aad3c7c69bd92572', 3, False]
    [2015/11/06 20:53:36] rpc: gettxout ['f80f5e6adaea8e1de3bbd6e26ee74d23cdaee5f45357ac37ca00fdbe3841ef8c', 0, False]
    [2015/11/06 20:53:36] fee breakdown for Tobayidaw totalin=294790770 cjamount=279928025 txfee=0 realcjfee=280
    [2015/11/06 20:53:36] got all parts, enough to build a tx

Accompanied with this issues error and then the loop begins again. Every time picking this bot as one of my makers. About 12 in a row I've tried and I cannot think of a way to block this one maker with a sweep.

**Comment by AdamISZ** [comment] 2015-11-06 21:13
@Xangst thanks for the detailed info. If one maker is causing an issue you can use -P to pick individual orders from makers, it's quite useful, although a bit tedious.

**Comment by Xangst** [comment] 2015-11-06 21:14
Not for a sweep.

**Comment by AdamISZ** [comment] 2015-11-06 21:15
Right.

**Comment by Xangst** [comment] 2015-11-06 21:34
If you've been watching the orderbook for the past 20 minutes you can see how many attempts I've made at sweeping 2.8 btc (20-30?) with one utxo of my own and a -N 2. I cannot get away from this Tobayidaw.

**Comment by AdamISZ** [comment] 2015-11-06 21:41
https://github.com/chris-belcher/joinmarket/blob/master/sendpayment.py#L32 <-- you could add it here.

Not a solution of course, but maybe it helps.

**Comment by chris-belcher** [comment] 2015-11-06 23:47
So what happened here, the maker Tobayidaw has lots of small UTXOs that add up to 2.8btc, the transaction is too large which causes the socket to crash for some reason?
My first guess is that the IRC code that breaks transactions into chunks and sends them down one-by-one is where the bug is. Given the "message not a cmd" print outs I'm almost sure of it.

@tailsjoin the tx from your log has a zero output and also an apparent negative miner fee. So something messed up.

**Comment by tailsjoin** [comment] 2015-11-07 00:40
Yeah, I'm not sure about that one. I can reproduce this almost any time with good txs. If you need some logs I can set up a test environment and get you some. I just purged my logs though about 5 minutes ago. Or if you want to do it just try a few sends for around 1 btc and you'll see it.

**Comment by chris-belcher** [comment] 2015-11-07 00:44
Stab in the dark: it was caused by this commit https://github.com/chris-belcher/joinmarket/commit/59a242304486ff5678ba2dc0635b57da988ef64c

Revert to before it and see if you get the bug?

**Comment by tailsjoin** [comment] 2015-11-07 01:10
If I just revert that commit the problem persists. If I roll back to before that commit I have incorrect padding error.

**Comment by tailsjoin** [comment] 2015-11-11 19:36
I'm losing 3/4 of the txs initiated by takers and I'm assuming it has to do with this bug. I used to have a 95%~ success rate when tx was initiated. Is anyone else experiencing this?

**Comment by AdamISZ** [comment] 2015-11-11 20:03
I couldn't give a number like that but I find it very variable; I can only say that I do, often, see incomplete transactions. Maybe it comes in bursts if one of the other makers is misbehaving?

In the last few days I've seen a high number of transactions compared to say, last week. I guess a relatively small percentage of failures (but haven't made a detailed check).

**Comment by AdamISZ** [comment] 2015-11-11 20:06
Edit: did a check for today, it's something like 10-15% from me, if I read the logs correctly.

**Comment by AdamISZ** [comment] 2016-09-15 12:14
AFAIU this was solved long ago by the throttling mechanism in IRC. Closing.

**Closed by AdamISZ** 2016-09-15 12:14 UTC
