### ISSUE TITLE
failed blockr.io pushtx, pushed tx None, unable to pushtx

### ISSUE THREAD

**Issue by lacksfish** [JoinMarket-Org/joinmarket#202] opened 2015-08-26 06:47 UTC
>[2015/08/26 08:41:44] failed blockr.io pushtx
>[2015/08/26 08:41:44] pushed tx None
>[2015/08/26 08:41:44] unable to pushtx

When pushtx to blockr.io fails, nothing happens. The only ongoing output is: 

> sharedtxid = set([])

**Comment by chris-belcher** [comment] 2015-08-26 16:06
What was the txhex ? Is it valid? If not, how did it get created, must be some bug.

**Comment by lacksfish** [comment] 2015-08-31 08:50
I'd rather not share it, sorry. The tx is valid. Created using the latest pull from your repo. Using mixing depth 1.

Support for another parser would be a good idea don't you think? Do you have preferences?

**Comment by chris-belcher** [comment] 2015-08-31 11:32
Yeah it's an open issue #64

**Comment by CohibAA** [comment] 2015-09-03 20:29
@lacksfish Not sure if related to your experience, but for reference, the same thing happens when trying to broadcast a coinjoin through blockr that does not include at least a 0.0001 fee.  This is the default for takers, but if the taker's fee is lowered and makers are picked/chosen whose fees do not total at least 0.0001, blockr will refuse the transaction and the output you quoted will show in the taker log.

FWIW, you may still be able to broadcast these transactions through [alternate broadcast nodes](https://en.bitcoin.it/wiki/Transaction_broadcasting) but you should be careful, as they may not get confirmed, particularly if the network is seeing lots of transactions.  Some of those nodes will also reject low and/or no fee transactions the same way blockr does.

**Comment by AdamISZ** [comment] 2016-09-15 12:18
This has not been reported since, perhaps because of the implementation of dynamic fees. That plus the fact that it's ancient is why I'm closing it.

**Closed by AdamISZ** 2016-09-15 12:18 UTC
Labels: Crash
